# Buildenv to build rustup
FROM opensuse/tumbleweed:latest

# Install build packages
RUN zypper install --no-confirm --type=pattern devel_basis \
    && zypper install --no-confirm cargo git rust

# Copy default cargo config and search for `cargo` to update the `crates.io index`
COPY files/config.toml /.cargo/config.toml
RUN cargo new /root/tmp \
    && cargo add --manifest-path /root/tmp/Cargo.toml libc \
    && rm -rf /root/tmp
