FROM alpine:edge

# Install build packages
RUN apk add --no-cache build-base cargo git rust

# Copy default cargo config and perform a best-effort cargo-search to update the crates.io-index
COPY files/config.toml /.cargo/config.toml
RUN cargo search --limit 0 || true
