# Buildenv to build rustup
FROM opensuse/tumbleweed:latest

# Install build packages
RUN zypper install --no-confirm --type=pattern devel_basis \
    && zypper install --no-confirm cargo git libopenssl-devel rust

# Copy default cargo config and perform a best-effort cargo-search to update the crates.io-index
COPY files/config.toml /.cargo/config.toml
RUN cargo search --limit 0 || true
